name: Deploy react app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "16.x" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: nicoinch/ghpages@v3.0.0-alpha-1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: yarn install
      - name: registry github user
        run: |
          git config --global user.email "jalesgervazzi@gmail.com"
          git config --global user.name "JoseAle2610"
          
      - name: deploy the app
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/JoseAle2610/JoseAle2610.github.io.git
          yarn run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
